# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: Your awesome title
email: imus.chloe@gmail.com
description: >
 Chloe is 24 and is currently working for Kickstarter, a proud Public Benefit Corporation. She’s previously been involved with other innovative brands like SoulCycle and GlobalGiving. She’s presently based out of Brooklyn but has explored, lived, or worked in 40 other countries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: coimus
github_username:  chloeimus

# Build settings
markdown: kramdown
